// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3uEOeSdnokf4weQgEk_nHPkSLkfMaCa8',
    appId: '1:605256249348:android:0fc9e351a565168468c551',
    messagingSenderId: '605256249348',
    projectId: 'fptproducthunt',
    databaseURL: 'https://fptproducthunt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fptproducthunt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPleJL4AkQRinzgktY2_dxEuHLvpaCVM',
    appId: '1:605256249348:ios:8dbd406b0f985fc268c551',
    messagingSenderId: '605256249348',
    projectId: 'fptproducthunt',
    databaseURL: 'https://fptproducthunt-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fptproducthunt.appspot.com',
    iosClientId: '605256249348-oqi7lfsmti42cb968oa3vlvml0d783qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.android',
  );
}
